-- Xmip Storage on SQL Server: the login.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a sysadmin with sqlcmd, its password given as the scripting
-- variable StoragePassword (sqlcmd -v StoragePassword=...), never in a file.

-- The login a Storage node connects as: reads and writes the tables,
-- nothing more.
CREATE LOGIN xmip_storage WITH PASSWORD = N'$(StoragePassword)', CHECK_POLICY = ON;
GO
