-- Xmip Storage on SQL Server: the administration database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a sysadmin with sqlcmd.

CREATE DATABASE xmip_administration;
GO
-- Every commit durable before it returns: Xmip counts a write once
-- the database has it (runtime-model.md section 3).
ALTER DATABASE xmip_administration SET DELAYED_DURABILITY = DISABLED;
GO
