-- Xmip Storage on PostgreSQL: the roles.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the postgres database.

-- Owns the schema; no one logs in as it. An operator who changes the
-- schema is granted it.
CREATE ROLE xmip_owner NOLOGIN;

-- The login a Storage node connects as: reads and writes the tables,
-- nothing more. Its password is set by the operator, never in a file:
-- \password xmip_storage
CREATE ROLE xmip_storage LOGIN;
