-- Xmip Storage on PostgreSQL: the audit database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the postgres database.

CREATE DATABASE xmip_audit OWNER xmip_owner ENCODING 'UTF8' TEMPLATE template0;
REVOKE ALL ON DATABASE xmip_audit FROM PUBLIC;
GRANT CONNECT ON DATABASE xmip_audit TO xmip_storage;
