-- Xmip Storage on PostgreSQL: the audit database's schema.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the xmip_audit database.

SET ROLE xmip_owner;
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;

-- audit records kept over time, each once, every single value of each in a column of its own, each in its writer's audit chain: its number there, the SHA-256 digest of the record before it and its own.
CREATE TABLE xmip.audit (
    id uuid NOT NULL,
    occurred_at timestamptz NOT NULL,
    kept_at timestamptz NOT NULL,
    action text NOT NULL,
    phase text NOT NULL,
    severity text NOT NULL,
    failed boolean NOT NULL,
    message_text text NULL,
    program text NOT NULL,
    host text NOT NULL,
    process integer NOT NULL,
    location text NULL,
    hidden boolean NOT NULL,
    execution uuid NULL,
    journey uuid NULL,
    message uuid NULL,
    artifact_kind text NULL,
    artifact_name text NULL,
    artifact_version text NULL,
    node text NULL,
    cluster text NULL,
    writer text NOT NULL,
    position bigint NOT NULL,
    previous_digest bytea NOT NULL,
    digest bytea NOT NULL,
    body_length bigint NOT NULL,
    body_chunks integer NOT NULL,
    body_digest bytea NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (id)
);

CREATE INDEX audit_occurred ON xmip.audit (occurred_at);

CREATE INDEX audit_journey ON xmip.audit (journey);

CREATE INDEX audit_message ON xmip.audit (message);

CREATE INDEX audit_artifact ON xmip.audit (artifact_name, occurred_at);

CREATE INDEX audit_failed ON xmip.audit (failed, occurred_at) WHERE failed;

CREATE INDEX audit_chain ON xmip.audit (writer, position);

-- where each writer's audit chain stands: the number of its last kept record and that record's SHA-256 digest, written with it by the audit keeper.
CREATE TABLE xmip.audit_chain_head (
    writer text NOT NULL,
    position bigint NOT NULL,
    digest bytea NOT NULL,
    CONSTRAINT audit_chain_head_key PRIMARY KEY (writer)
);

-- the body of each kept audit record, its record and the Message it carries, in chunks by the record's identifier and their number, as a Stream is kept, written with it by the audit keeper.
CREATE TABLE xmip.audit_body_chunk (
    audit uuid NOT NULL,
    chunk integer NOT NULL,
    bytes bytea NOT NULL,
    CONSTRAINT audit_body_chunk_key PRIMARY KEY (audit, chunk)
);

-- each Stream a kept audit record carries, once: its length, its chunks, the SHA-256 digest of its bytes and when the Ledger wrote it, written with the record by the audit keeper.
CREATE TABLE xmip.audit_stream (
    audit uuid NOT NULL,
    stream uuid NOT NULL,
    length bigint NOT NULL,
    chunks integer NOT NULL,
    digest bytea NOT NULL,
    written_at timestamptz NOT NULL,
    CONSTRAINT audit_stream_key PRIMARY KEY (audit, stream)
);

CREATE INDEX audit_stream_stream ON xmip.audit_stream (stream);

-- the bytes of each Stream a kept audit record carries, in chunks by the record's identifier, the Stream's and their number, kept with it by the audit keeper; a Stream two Sections share once.
CREATE TABLE xmip.audit_stream_chunk (
    audit uuid NOT NULL,
    stream uuid NOT NULL,
    chunk integer NOT NULL,
    bytes bytea NOT NULL,
    CONSTRAINT audit_stream_chunk_key PRIMARY KEY (audit, stream, chunk)
);

GRANT USAGE ON SCHEMA xmip TO xmip_storage;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA xmip TO xmip_storage;
RESET ROLE;
