-- Xmip Storage on PostgreSQL: the administration database's schema.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the xmip_administration database.

SET ROLE xmip_owner;
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;

-- registration, membership, Modules, Handlers, deployment and operator state, and when each was last written.
CREATE TABLE xmip.administration (
    kind text NOT NULL,
    id uuid NOT NULL,
    body bytea NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT administration_key PRIMARY KEY (kind, id)
);

CREATE INDEX administration_updated ON xmip.administration (kind, updated_at);

GRANT USAGE ON SCHEMA xmip TO xmip_storage;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA xmip TO xmip_storage;
RESET ROLE;
