-- Xmip Storage on PostgreSQL: the runtime database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the xmip_runtime database.

SET ROLE xmip_owner;
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;

-- every Stream, in chunks.
CREATE TABLE xmip.stream_chunk (
    stream uuid NOT NULL,
    chunk integer NOT NULL,
    last boolean NOT NULL,
    bytes bytea NOT NULL,
    CONSTRAINT stream_chunk_key PRIMARY KEY (stream, chunk)
);

-- every Message, as a step wrote it.
CREATE TABLE xmip.message (
    message uuid NOT NULL,
    body bytea NOT NULL,
    CONSTRAINT message_key PRIMARY KEY (message)
);

-- every Journey, as a step wrote it.
CREATE TABLE xmip.journey (
    journey uuid NOT NULL,
    body bytea NOT NULL,
    CONSTRAINT journey_key PRIMARY KEY (journey)
);

-- the claim on each Journey: its holder, its token, when it lapses.
CREATE TABLE xmip.claim (
    journey uuid NOT NULL,
    holder text NOT NULL,
    token uuid NOT NULL,
    until_unix_nanos bigint NOT NULL,
    released boolean NOT NULL,
    CONSTRAINT claim_key PRIMARY KEY (journey)
);

-- audit records as first written, until the audit keeper moves them.
CREATE TABLE xmip.audit (
    sequence bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    id uuid NOT NULL,
    body bytea NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (sequence)
);

GRANT USAGE ON SCHEMA xmip TO xmip_storage;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA xmip TO xmip_storage;
RESET ROLE;
