-- Xmip Storage on PostgreSQL: the runtime database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the xmip_runtime database.

SET ROLE xmip_owner;
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;

-- every Stream, in chunks.
CREATE TABLE xmip.stream_chunk (
    stream uuid NOT NULL,
    chunk integer NOT NULL,
    last boolean NOT NULL,
    bytes bytea NOT NULL,
    CONSTRAINT stream_chunk_key PRIMARY KEY (stream, chunk)
);

-- every Message, as a step wrote it, every single value of it in a column of its own.
CREATE TABLE xmip.message (
    message uuid NOT NULL,
    body bytea NOT NULL,
    created_at timestamptz NOT NULL,
    previous_message uuid NULL,
    generation integer NOT NULL,
    created_by smallint NOT NULL,
    priority smallint NOT NULL,
    execution_profile smallint NOT NULL,
    durability smallint NOT NULL,
    size_bytes bigint NOT NULL,
    party text NULL,
    contract text NULL,
    stream uuid NULL,
    CONSTRAINT message_key PRIMARY KEY (message)
);

CREATE INDEX message_created ON xmip.message (created_at);

CREATE INDEX message_party ON xmip.message (party, created_at);

CREATE INDEX message_contract ON xmip.message (contract, created_at);

CREATE INDEX message_previous ON xmip.message (previous_message);

-- every Journey, as a step wrote it, every single value of it in a column of its own.
CREATE TABLE xmip.journey (
    journey uuid NOT NULL,
    body bytea NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    state smallint NOT NULL,
    previous_journey uuid NULL,
    subscription text NULL,
    cause_work_process text NULL,
    depth integer NOT NULL,
    work_process text NULL,
    send_port text NULL,
    send_location integer NOT NULL,
    attempts integer NOT NULL,
    message uuid NULL,
    CONSTRAINT journey_key PRIMARY KEY (journey)
);

CREATE INDEX journey_state ON xmip.journey (state, updated_at);

CREATE INDEX journey_send_port ON xmip.journey (send_port, state);

CREATE INDEX journey_previous ON xmip.journey (previous_journey);

CREATE INDEX journey_message ON xmip.journey (message);

-- the Journeys a paused Subscription holds, at their place in its queue, each once.
CREATE TABLE xmip.held (
    queue uuid NOT NULL,
    sequence bigint NOT NULL,
    journey uuid NOT NULL,
    body bytea NOT NULL,
    held_at timestamptz NOT NULL,
    CONSTRAINT held_key PRIMARY KEY (queue, sequence),
    CONSTRAINT held_unique UNIQUE (queue, journey)
);

CREATE INDEX held_time ON xmip.held (queue, held_at);

-- each queue's first place, its next and how many it holds.
CREATE TABLE xmip.held_places (
    queue uuid NOT NULL,
    first_place bigint NOT NULL,
    next_place bigint NOT NULL,
    held bigint NOT NULL,
    CONSTRAINT held_places_key PRIMARY KEY (queue)
);

-- each node's Dead Message Queue: every Message nothing matched, at its place, with its receive context, what its gates concluded, its promoted properties and each Subscription's reason for declining, each once.
CREATE TABLE xmip.dead_message (
    queue uuid NOT NULL,
    sequence bigint NOT NULL,
    message uuid NOT NULL,
    body bytea NOT NULL,
    stream uuid NOT NULL,
    node text NOT NULL,
    receive_location text NOT NULL,
    queued_at timestamptz NOT NULL,
    CONSTRAINT dead_message_key PRIMARY KEY (queue, sequence),
    CONSTRAINT dead_message_unique UNIQUE (queue, message)
);

CREATE INDEX dead_message_time ON xmip.dead_message (queue, queued_at);

-- each Dead Message Queue's first place, its next and how many it holds.
CREATE TABLE xmip.dead_message_places (
    queue uuid NOT NULL,
    first_place bigint NOT NULL,
    next_place bigint NOT NULL,
    held bigint NOT NULL,
    CONSTRAINT dead_message_places_key PRIMARY KEY (queue)
);

-- each Message replayed from a Dead Message Queue, so a Replay asked again writes nothing twice.
CREATE TABLE xmip.dead_message_replayed (
    queue uuid NOT NULL,
    message uuid NOT NULL,
    CONSTRAINT dead_message_replayed_key PRIMARY KEY (queue, message)
);

-- each Message published, with the digest of its Publication, so a Publication asked again writes nothing and resets no Journey moved on since.
CREATE TABLE xmip.publication (
    message uuid NOT NULL,
    digest bytea NOT NULL,
    CONSTRAINT publication_key PRIMARY KEY (message)
);

-- the claim on each Journey: its holder, its token, when it lapses, and whether it was given back or its step handed on.
CREATE TABLE xmip.claim (
    journey uuid NOT NULL,
    holder text NOT NULL,
    token uuid NOT NULL,
    until_unix_nanos bigint NOT NULL,
    released boolean NOT NULL,
    handed_on boolean NOT NULL,
    CONSTRAINT claim_key PRIMARY KEY (journey)
);

-- audit records as first written, until the audit keeper moves them.
CREATE TABLE xmip.audit (
    sequence bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    id uuid NOT NULL,
    body bytea NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (sequence)
);

GRANT USAGE ON SCHEMA xmip TO xmip_storage;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA xmip TO xmip_storage;
RESET ROLE;
