-- Xmip Storage on PostgreSQL: the administration database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the xmip_administration database.

SET ROLE xmip_owner;
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;

-- audit records kept over time, each once, every single value of each in a column of its own.
CREATE TABLE xmip.audit (
    id uuid NOT NULL,
    body bytea NOT NULL,
    occurred_at timestamptz NOT NULL,
    kept_at timestamptz NOT NULL,
    action text NOT NULL,
    phase text NOT NULL,
    severity text NOT NULL,
    failed boolean NOT NULL,
    message_text text NULL,
    program text NOT NULL,
    host text NOT NULL,
    process integer NOT NULL,
    location text NULL,
    hidden boolean NOT NULL,
    execution uuid NULL,
    journey uuid NULL,
    message uuid NULL,
    artifact_kind text NULL,
    artifact_name text NULL,
    artifact_version text NULL,
    node text NULL,
    cluster text NULL,
    stream_digest bytea NULL,
    stream_length bigint NULL,
    CONSTRAINT audit_key PRIMARY KEY (id)
);

CREATE INDEX audit_occurred ON xmip.audit (occurred_at);

CREATE INDEX audit_journey ON xmip.audit (journey);

CREATE INDEX audit_message ON xmip.audit (message);

CREATE INDEX audit_artifact ON xmip.audit (artifact_name, occurred_at);

CREATE INDEX audit_failed ON xmip.audit (failed, occurred_at) WHERE failed;

-- the bytes of the Stream a kept audit record carries, in chunks by the record's identifier and their number, kept with it by the audit keeper.
CREATE TABLE xmip.audit_stream_chunk (
    audit uuid NOT NULL,
    chunk integer NOT NULL,
    bytes bytea NOT NULL,
    CONSTRAINT audit_stream_chunk_key PRIMARY KEY (audit, chunk)
);

-- registration, membership, Modules, Handlers, deployment and operator state, and when each was last written.
CREATE TABLE xmip.administration (
    kind text NOT NULL,
    id uuid NOT NULL,
    body bytea NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT administration_key PRIMARY KEY (kind, id)
);

CREATE INDEX administration_updated ON xmip.administration (kind, updated_at);

GRANT USAGE ON SCHEMA xmip TO xmip_storage;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA xmip TO xmip_storage;
RESET ROLE;
