-- Xmip Storage on PostgreSQL: the administration database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a superuser, connected to the xmip_administration database.

SET ROLE xmip_owner;
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;

-- audit records kept over time, each once.
CREATE TABLE xmip.audit (
    id uuid NOT NULL,
    body bytea NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (id)
);

-- registration, membership, Modules, Handlers, deployment and operator state.
CREATE TABLE xmip.administration (
    kind text NOT NULL,
    id uuid NOT NULL,
    body bytea NOT NULL,
    CONSTRAINT administration_key PRIMARY KEY (kind, id)
);

GRANT USAGE ON SCHEMA xmip TO xmip_storage;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA xmip TO xmip_storage;
RESET ROLE;
