-- Xmip Storage on SQL Server: the runtime database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a sysadmin with sqlcmd.

USE xmip_runtime;
GO
CREATE ROLE xmip_owner;
GO
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;
GO

-- every Stream, in chunks.
CREATE TABLE xmip.stream_chunk (
    stream binary(16) NOT NULL,
    chunk int NOT NULL,
    last bit NOT NULL,
    bytes varbinary(max) NOT NULL,
    CONSTRAINT stream_chunk_key PRIMARY KEY (stream, chunk)
);
GO

-- every Message, as a step wrote it, and what it is searched by.
CREATE TABLE xmip.message (
    message binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    created_at datetime2(7) NOT NULL,
    generation int NOT NULL,
    created_by smallint NOT NULL,
    size_bytes bigint NOT NULL,
    previous_message_ref binary(16) NULL,
    party_ref binary(16) NULL,
    contract_ref binary(16) NULL,
    stream_ref binary(16) NULL,
    CONSTRAINT message_key PRIMARY KEY (message)
);
GO

CREATE INDEX message_created ON xmip.message (created_at);
GO

CREATE INDEX message_party ON xmip.message (party_ref, created_at);
GO

CREATE INDEX message_contract ON xmip.message (contract_ref, created_at);
GO

CREATE INDEX message_previous ON xmip.message (previous_message_ref);
GO

-- every Journey, as a step wrote it, and what it is searched by.
CREATE TABLE xmip.journey (
    journey binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    created_at datetime2(7) NOT NULL,
    updated_at datetime2(7) NOT NULL,
    state smallint NOT NULL,
    attempts int NOT NULL,
    depth int NOT NULL,
    send_port_ref binary(16) NULL,
    work_process_ref binary(16) NULL,
    previous_journey_ref binary(16) NULL,
    message_ref binary(16) NULL,
    CONSTRAINT journey_key PRIMARY KEY (journey)
);
GO

CREATE INDEX journey_state ON xmip.journey (state, updated_at);
GO

CREATE INDEX journey_send_port ON xmip.journey (send_port_ref, state);
GO

CREATE INDEX journey_previous ON xmip.journey (previous_journey_ref);
GO

CREATE INDEX journey_message ON xmip.journey (message_ref);
GO

-- the Journeys a paused Subscription holds, at their place in its queue, each once.
CREATE TABLE xmip.held (
    queue binary(16) NOT NULL,
    sequence bigint NOT NULL,
    journey binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    held_at datetime2(7) NOT NULL,
    CONSTRAINT held_key PRIMARY KEY (queue, sequence),
    CONSTRAINT held_unique UNIQUE (queue, journey)
);
GO

CREATE INDEX held_time ON xmip.held (queue, held_at);
GO

-- each queue's first place, its next and how many it holds.
CREATE TABLE xmip.held_places (
    queue binary(16) NOT NULL,
    first_place bigint NOT NULL,
    next_place bigint NOT NULL,
    held bigint NOT NULL,
    CONSTRAINT held_places_key PRIMARY KEY (queue)
);
GO

-- each node's Dead Message Queue: every Message nothing matched, at its place, with its receive context, what its gates concluded, its promoted properties and each Subscription's reason for declining, each once.
CREATE TABLE xmip.dead_message (
    queue binary(16) NOT NULL,
    sequence bigint NOT NULL,
    message binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    queued_at datetime2(7) NOT NULL,
    node_ref binary(16) NOT NULL,
    receive_location_ref binary(16) NOT NULL,
    CONSTRAINT dead_message_key PRIMARY KEY (queue, sequence),
    CONSTRAINT dead_message_unique UNIQUE (queue, message)
);
GO

CREATE INDEX dead_message_time ON xmip.dead_message (queue, queued_at);
GO

-- each Dead Message Queue's first place, its next and how many it holds.
CREATE TABLE xmip.dead_message_places (
    queue binary(16) NOT NULL,
    first_place bigint NOT NULL,
    next_place bigint NOT NULL,
    held bigint NOT NULL,
    CONSTRAINT dead_message_places_key PRIMARY KEY (queue)
);
GO

-- each Message replayed from a Dead Message Queue, so a Replay asked again writes nothing twice.
CREATE TABLE xmip.dead_message_replayed (
    queue binary(16) NOT NULL,
    message binary(16) NOT NULL,
    CONSTRAINT dead_message_replayed_key PRIMARY KEY (queue, message)
);
GO

-- each Message published, with the digest of its Publication, so a Publication asked again writes nothing and resets no Journey moved on since.
CREATE TABLE xmip.publication (
    message binary(16) NOT NULL,
    digest varbinary(max) NOT NULL,
    CONSTRAINT publication_key PRIMARY KEY (message)
);
GO

-- the claim on each Journey: its holder, its token, when it lapses, and whether it was given back or its step handed on.
CREATE TABLE xmip.claim (
    journey binary(16) NOT NULL,
    holder nvarchar(400) NOT NULL,
    token binary(16) NOT NULL,
    until_unix_nanos bigint NOT NULL,
    released bit NOT NULL,
    handed_on bit NOT NULL,
    CONSTRAINT claim_key PRIMARY KEY (journey)
);
GO

-- audit records as first written, until the audit keeper moves them.
CREATE TABLE xmip.audit (
    sequence bigint IDENTITY(1, 1) NOT NULL,
    id binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (sequence)
);
GO

CREATE USER xmip_storage FOR LOGIN xmip_storage;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::xmip TO xmip_storage;
GO
