-- Xmip Storage on SQL Server: the runtime database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a sysadmin with sqlcmd.

USE xmip_runtime;
GO
CREATE ROLE xmip_owner;
GO
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;
GO

-- every Stream, in chunks.
CREATE TABLE xmip.stream_chunk (
    stream binary(16) NOT NULL,
    chunk int NOT NULL,
    last bit NOT NULL,
    bytes varbinary(max) NOT NULL,
    CONSTRAINT stream_chunk_key PRIMARY KEY (stream, chunk)
);
GO

-- every Message, as a step wrote it.
CREATE TABLE xmip.message (
    message binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    CONSTRAINT message_key PRIMARY KEY (message)
);
GO

-- every Journey, as a step wrote it.
CREATE TABLE xmip.journey (
    journey binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    CONSTRAINT journey_key PRIMARY KEY (journey)
);
GO

-- the claim on each Journey: its holder, its token, when it lapses.
CREATE TABLE xmip.claim (
    journey binary(16) NOT NULL,
    holder nvarchar(400) NOT NULL,
    token binary(16) NOT NULL,
    until_unix_nanos bigint NOT NULL,
    released bit NOT NULL,
    CONSTRAINT claim_key PRIMARY KEY (journey)
);
GO

-- audit records as first written, until the audit keeper moves them.
CREATE TABLE xmip.audit (
    sequence bigint IDENTITY(1, 1) NOT NULL,
    id binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (sequence)
);
GO

CREATE USER xmip_storage FOR LOGIN xmip_storage;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::xmip TO xmip_storage;
GO
