-- Xmip Storage on SQL Server: the administration database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a sysadmin with sqlcmd.

USE xmip_administration;
GO
CREATE ROLE xmip_owner;
GO
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;
GO

-- audit records kept over time, each once.
CREATE TABLE xmip.audit (
    id binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (id)
);
GO

-- registration, membership, Modules, Handlers, deployment and operator state.
CREATE TABLE xmip.administration (
    kind nvarchar(400) NOT NULL,
    id binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    CONSTRAINT administration_key PRIMARY KEY (kind, id)
);
GO

CREATE USER xmip_storage FOR LOGIN xmip_storage;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::xmip TO xmip_storage;
GO
