-- Xmip Storage on SQL Server: the administration database.
--
-- Generated by xmip-core-persist (storage::schema), the definition the
-- backend reads and writes by; do not edit. `cargo test --test database`
-- at the estate root fails when this file differs from what it writes.
-- What to run, in what order and why: README.md beside this file.
--
-- Run as a sysadmin with sqlcmd.

USE xmip_administration;
GO
CREATE ROLE xmip_owner;
GO
CREATE SCHEMA xmip AUTHORIZATION xmip_owner;
GO

-- audit records kept over time, each once, every single value of each in a column of its own, each in its writer's audit chain: its number there, the SHA-256 digest of the record before it and its own.
CREATE TABLE xmip.audit (
    id binary(16) NOT NULL,
    occurred_at datetime2(7) NOT NULL,
    kept_at datetime2(7) NOT NULL,
    action nvarchar(400) NOT NULL,
    phase nvarchar(32) NOT NULL,
    severity nvarchar(32) NOT NULL,
    failed bit NOT NULL,
    message_text nvarchar(max) NULL,
    program nvarchar(400) NOT NULL,
    host nvarchar(400) NOT NULL,
    process int NOT NULL,
    location nvarchar(400) NULL,
    hidden bit NOT NULL,
    execution binary(16) NULL,
    journey binary(16) NULL,
    message binary(16) NULL,
    artifact_kind nvarchar(32) NULL,
    artifact_name nvarchar(400) NULL,
    artifact_version nvarchar(400) NULL,
    node nvarchar(400) NULL,
    cluster nvarchar(400) NULL,
    writer nvarchar(400) NOT NULL,
    position bigint NOT NULL,
    previous_digest varbinary(max) NOT NULL,
    digest varbinary(max) NOT NULL,
    body_length bigint NOT NULL,
    body_chunks int NOT NULL,
    body_digest varbinary(max) NOT NULL,
    CONSTRAINT audit_key PRIMARY KEY (id)
);
GO

CREATE INDEX audit_occurred ON xmip.audit (occurred_at);
GO

CREATE INDEX audit_journey ON xmip.audit (journey);
GO

CREATE INDEX audit_message ON xmip.audit (message);
GO

CREATE INDEX audit_artifact ON xmip.audit (artifact_name, occurred_at);
GO

CREATE INDEX audit_failed ON xmip.audit (failed, occurred_at) WHERE failed = 1;
GO

CREATE INDEX audit_chain ON xmip.audit (writer, position);
GO

-- where each writer's audit chain stands: the number of its last kept record and that record's SHA-256 digest, written with it by the audit keeper.
CREATE TABLE xmip.audit_chain_head (
    writer nvarchar(400) NOT NULL,
    position bigint NOT NULL,
    digest varbinary(max) NOT NULL,
    CONSTRAINT audit_chain_head_key PRIMARY KEY (writer)
);
GO

-- the body of each kept audit record, its record and the Message it carries, in chunks by the record's identifier and their number, as a Stream is kept, written with it by the audit keeper.
CREATE TABLE xmip.audit_body_chunk (
    audit binary(16) NOT NULL,
    chunk int NOT NULL,
    bytes varbinary(max) NOT NULL,
    CONSTRAINT audit_body_chunk_key PRIMARY KEY (audit, chunk)
);
GO

-- each Stream a kept audit record carries, once: its length, its chunks, the SHA-256 digest of its bytes and when the Ledger wrote it, written with the record by the audit keeper.
CREATE TABLE xmip.audit_stream (
    audit binary(16) NOT NULL,
    stream binary(16) NOT NULL,
    length bigint NOT NULL,
    chunks int NOT NULL,
    digest varbinary(max) NOT NULL,
    written_at datetime2(7) NOT NULL,
    CONSTRAINT audit_stream_key PRIMARY KEY (audit, stream)
);
GO

CREATE INDEX audit_stream_stream ON xmip.audit_stream (stream);
GO

-- the bytes of each Stream a kept audit record carries, in chunks by the record's identifier, the Stream's and their number, kept with it by the audit keeper; a Stream two Sections share once.
CREATE TABLE xmip.audit_stream_chunk (
    audit binary(16) NOT NULL,
    stream binary(16) NOT NULL,
    chunk int NOT NULL,
    bytes varbinary(max) NOT NULL,
    CONSTRAINT audit_stream_chunk_key PRIMARY KEY (audit, stream, chunk)
);
GO

-- registration, membership, Modules, Handlers, deployment and operator state, and when each was last written.
CREATE TABLE xmip.administration (
    kind nvarchar(32) NOT NULL,
    id binary(16) NOT NULL,
    body varbinary(max) NOT NULL,
    updated_at datetime2(7) NOT NULL,
    CONSTRAINT administration_key PRIMARY KEY (kind, id)
);
GO

CREATE INDEX administration_updated ON xmip.administration (kind, updated_at);
GO

CREATE USER xmip_storage FOR LOGIN xmip_storage;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::xmip TO xmip_storage;
GO
