//! `--definition`: what this platform's service manager is told about the
//! node's Xmip Service, generated by `registration.rs` — the one place it is
//! written — for this executable, this configuration and the node it names.
//! An installer registers what it prints; nothing here registers anything,
//! since registering needs elevation (ADR-0018, Open).

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use xmip_audit::program_audit::ProgramAudit;
use xmip_runtime::registration::{
    REFUSED, ServiceDefinition, ServiceManager, launchd_plist, systemd_unit,
    windows_service_arguments,
};

use crate::arguments::Arguments;
use crate::run;

/// Print the definition, or refuse in words.
pub fn print(audit: &ProgramAudit, arguments: &Arguments) -> ExitCode {
    match definition(arguments) {
        Ok(text) => {
            print!("{text}");
            ExitCode::SUCCESS
        }
        Err(problem) => {
            run::fail(audit, "definition", &format!("xmip-service: {problem}"));
            ExitCode::from(REFUSED)
        }
    }
}

fn definition(arguments: &Arguments) -> Result<String, String> {
    let (document, _, _) =
        xmip_runtime::start::read(&arguments.configuration).map_err(|unread| unread.reason)?;
    let executable = std::env::current_exe()
        .map_err(|error| format!("cannot say where this executable is: {error}"))?;
    let configuration = std::path::absolute(&arguments.configuration)
        .map_err(|error| format!("{}: {error}", arguments.configuration))?;
    let service = ServiceDefinition::for_node(
        &document.service.node_name,
        &text(&executable),
        &text(&configuration),
        &text(&installed_root(&executable)),
    );
    render(ServiceManager::for_target(), &service)
}

/// What `manager` is told, as text.
fn render(manager: ServiceManager, service: &ServiceDefinition) -> Result<String, String> {
    match manager {
        ServiceManager::Systemd => Ok(systemd_unit(service)),
        ServiceManager::Launchd => Ok(launchd_plist(service)),
        ServiceManager::WindowsScm => Ok(windows_service_arguments(service)
            .into_iter()
            .map(|argument| argument + "\n")
            .collect()),
        ServiceManager::None => Err("this platform has no service manager".to_string()),
    }
}

/// The installed layout's root, which the executable's `bin` sits in
/// (ADR-0015 clause 10); the executable's own directory where it sits in no
/// `bin`.
fn installed_root(executable: &Path) -> PathBuf {
    let directory = executable.parent().unwrap_or(executable);
    if directory.file_name().is_some_and(|name| name == "bin") {
        directory.parent().unwrap_or(directory).to_path_buf()
    } else {
        directory.to_path_buf()
    }
}

fn text(path: &Path) -> String {
    path.display().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_root_is_the_layout_the_executable_is_installed_in() {
        let root = Path::new("/opt/xmip");
        assert_eq!(installed_root(&root.join("bin/xmip-service")), root);
        assert_eq!(
            installed_root(Path::new("/home/me/target/debug/xmip-service")),
            Path::new("/home/me/target/debug")
        );
    }

    #[test]
    fn each_manager_gets_its_own_form_of_the_one_definition() {
        let service = ServiceDefinition::for_node(
            "alpha",
            "/opt/xmip/bin/xmip-service",
            "/opt/xmip/config/xmip-node.toml",
            "/opt/xmip",
        );

        let unit = render(ServiceManager::Systemd, &service).expect("a unit");
        assert!(unit.contains("ExecStart=/opt/xmip/bin/xmip-service --configuration"));
        let plist = render(ServiceManager::Launchd, &service).expect("a plist");
        assert!(plist.contains("<string>xmip-alpha</string>"));
        let scm = render(ServiceManager::WindowsScm, &service).expect("arguments");
        assert!(scm.starts_with("create\nxmip-alpha\nbinPath= "), "{scm}");
        assert!(render(ServiceManager::None, &service).is_err());
    }
}
