$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
parameters:
  labConfig:
    type: string
    defaultValue: D:/Repos/Xmip/.local-work/hyperv-lab/lab.json
resources:
  - name: HyperVHost
    type: Xmip.Lab/HyperVHost
    properties:
      ConfigPath: "[parameters('labConfig')]"
  - name: WindowsGuests
    type: Xmip.Lab/WindowsGuests
    dependsOn:
      - "[resourceId('Xmip.Lab/HyperVHost', 'HyperVHost')]"
    properties:
      ConfigPath: "[parameters('labConfig')]"
