use crate::handler_universe::{HandlerRepository, HandlerSpace};

pub const BUSINESS_HANDLER_REPOSITORIES: &[HandlerRepository] = &[
    HandlerRepository { repository_name: "xmip-handler-queue-stream-common", submodule_path: "handlers/queue-stream/common", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-msmq", submodule_path: "handlers/queue-stream/msmq", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-rabbitmq", submodule_path: "handlers/queue-stream/rabbitmq", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-kafka", submodule_path: "handlers/queue-stream/apache-kafka", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-ibmmq", submodule_path: "handlers/queue-stream/ibmmq", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-amqp", submodule_path: "handlers/queue-stream/amqp", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-stomp", submodule_path: "handlers/queue-stream/stomp", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-azure-service-bus", submodule_path: "handlers/queue-stream/azure-service-bus", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-azure-event-grid", submodule_path: "handlers/queue-stream/azure-event-grid", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-azure-event-hubs", submodule_path: "handlers/queue-stream/azure-event-hubs", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-aws-sqs", submodule_path: "handlers/queue-stream/aws-sqs", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-aws-sns", submodule_path: "handlers/queue-stream/aws-sns", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-google-pubsub", submodule_path: "handlers/queue-stream/google-pubsub", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-nats", submodule_path: "handlers/queue-stream/nats", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-redis-streams", submodule_path: "handlers/queue-stream/redis-streams", space: HandlerSpace::MessagingStreaming },
    HandlerRepository { repository_name: "xmip-handler-as2", submodule_path: "handlers/file-transfer/as2", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-as4", submodule_path: "handlers/file-transfer/as4", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-oftp2", submodule_path: "handlers/file-transfer/oftp2", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-data-exchange-common", submodule_path: "handlers/data-exchange/common", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-edi", submodule_path: "handlers/data-exchange/edi", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-x12", submodule_path: "handlers/data-exchange/x12", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-edifact", submodule_path: "handlers/data-exchange/edifact", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-peppol", submodule_path: "handlers/data-exchange/peppol", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-ubl", submodule_path: "handlers/data-exchange/ubl", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-rosettanet", submodule_path: "handlers/data-exchange/rosettanet", space: HandlerSpace::BusinessDocuments },
    HandlerRepository { repository_name: "xmip-handler-hl7", submodule_path: "handlers/healthcare/hl7", space: HandlerSpace::Healthcare },
    HandlerRepository { repository_name: "xmip-handler-fhir", submodule_path: "handlers/healthcare/fhir", space: HandlerSpace::Healthcare },
    HandlerRepository { repository_name: "xmip-handler-dicom", submodule_path: "handlers/healthcare/dicom", space: HandlerSpace::Healthcare },
];
