use crate::handler_universe::{HandlerRepository, HandlerSpace};

pub const ENTERPRISE_HANDLER_REPOSITORIES: &[HandlerRepository] = &[
    HandlerRepository { repository_name: "xmip-handler-db-common", submodule_path: "handlers/database/common", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-postgresql", submodule_path: "handlers/database/postgresql", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-mysql", submodule_path: "handlers/database/mysql", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-mssql", submodule_path: "handlers/database/mssql", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-oracle-db", submodule_path: "handlers/database/oracle-db", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-db2", submodule_path: "handlers/database/db2", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-sqlite", submodule_path: "handlers/database/sqlite", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-mongodb", submodule_path: "handlers/database/mongodb", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-cassandra", submodule_path: "handlers/database/cassandra", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-elasticsearch", submodule_path: "handlers/database/elasticsearch", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-s3", submodule_path: "handlers/storage/s3", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-azure-blob", submodule_path: "handlers/storage/azure-blob", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-google-cloud-storage", submodule_path: "handlers/storage/google-cloud-storage", space: HandlerSpace::DatabaseStorage },
    HandlerRepository { repository_name: "xmip-handler-smtp", submodule_path: "handlers/email/smtp", space: HandlerSpace::EmailCollaboration },
    HandlerRepository { repository_name: "xmip-handler-imap", submodule_path: "handlers/email/imap", space: HandlerSpace::EmailCollaboration },
    HandlerRepository { repository_name: "xmip-handler-pop3", submodule_path: "handlers/email/pop3", space: HandlerSpace::EmailCollaboration },
    HandlerRepository { repository_name: "xmip-handler-microsoft-graph", submodule_path: "handlers/collaboration/microsoft-graph", space: HandlerSpace::EmailCollaboration },
    HandlerRepository { repository_name: "xmip-handler-sharepoint", submodule_path: "handlers/collaboration/sharepoint", space: HandlerSpace::EmailCollaboration },
    HandlerRepository { repository_name: "xmip-handler-sap", submodule_path: "handlers/enterprise/sap", space: HandlerSpace::EnterpriseSaaS },
    HandlerRepository { repository_name: "xmip-handler-salesforce", submodule_path: "handlers/enterprise/salesforce", space: HandlerSpace::EnterpriseSaaS },
    HandlerRepository { repository_name: "xmip-handler-dynamics", submodule_path: "handlers/enterprise/dynamics", space: HandlerSpace::EnterpriseSaaS },
    HandlerRepository { repository_name: "xmip-handler-servicenow", submodule_path: "handlers/enterprise/servicenow", space: HandlerSpace::EnterpriseSaaS },
    HandlerRepository { repository_name: "xmip-handler-oauth2", submodule_path: "handlers/identity/oauth2", space: HandlerSpace::IdentityDirectory },
    HandlerRepository { repository_name: "xmip-handler-oidc", submodule_path: "handlers/identity/oidc", space: HandlerSpace::IdentityDirectory },
    HandlerRepository { repository_name: "xmip-handler-saml", submodule_path: "handlers/identity/saml", space: HandlerSpace::IdentityDirectory },
    HandlerRepository { repository_name: "xmip-handler-ldap", submodule_path: "handlers/identity/ldap", space: HandlerSpace::IdentityDirectory },
    HandlerRepository { repository_name: "xmip-handler-kerberos", submodule_path: "handlers/identity/kerberos", space: HandlerSpace::IdentityDirectory },
    HandlerRepository { repository_name: "xmip-handler-swift", submodule_path: "handlers/finance/swift", space: HandlerSpace::FinancePayments },
    HandlerRepository { repository_name: "xmip-handler-iso-20022", submodule_path: "handlers/finance/iso-20022", space: HandlerSpace::FinancePayments },
    HandlerRepository { repository_name: "xmip-handler-fix", submodule_path: "handlers/finance/fix", space: HandlerSpace::FinancePayments },
    HandlerRepository { repository_name: "xmip-handler-x-road", submodule_path: "handlers/government/x-road", space: HandlerSpace::GovernmentExchange },
    HandlerRepository { repository_name: "xmip-handler-ogc-api", submodule_path: "handlers/geospatial/ogc-api", space: HandlerSpace::Geospatial },
    HandlerRepository { repository_name: "xmip-handler-wms", submodule_path: "handlers/geospatial/wms", space: HandlerSpace::Geospatial },
    HandlerRepository { repository_name: "xmip-handler-wfs", submodule_path: "handlers/geospatial/wfs", space: HandlerSpace::Geospatial },
];
