#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HandlerFamily {
    File,
    FileTransfer,
    Tcp,
    Udp,
    Http,
    Grpc,
    Healthcare,
    DataExchange,
    QueueStream,
    IndustrialDevice,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HandlerTechnology {
    File,
    Ftp,
    TcpBase,
    RawTcp,
    UdpBase,
    RawUdp,
    Http,
    WebApi,
    Soap,
    WebSocket,
    Grpc,
    Mllp,
    QueueStreamCommon,
    Msmq,
    RabbitMq,
    Kafka,
    IbmMq,
    AzureServiceBus,
    AzureEventGrid,
    AwsSqs,
    Nats,
    RedisStreams,
    IndustrialDeviceCommon,
    Canbus,
    OpcUa,
    Modbus,
    Mqtt,
    DataExchangeCommon,
    Edi,
    Hl7,
    Fhir,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HandlerTechnologyDescriptor {
    pub technology: HandlerTechnology,
    pub family: HandlerFamily,
    pub repository_name: &'static str,
    pub submodule_path: &'static str,
}

pub const HANDLER_TECHNOLOGIES: &[HandlerTechnologyDescriptor] = &[
    HandlerTechnologyDescriptor { technology: HandlerTechnology::File, family: HandlerFamily::File, repository_name: "xmip-handler-file", submodule_path: "handlers/file" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Ftp, family: HandlerFamily::FileTransfer, repository_name: "xmip-handler-ftp", submodule_path: "handlers/file-transfer/ftp" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::TcpBase, family: HandlerFamily::Tcp, repository_name: "xmip-handler-tcp-base", submodule_path: "handlers/ip/tcp/base" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::RawTcp, family: HandlerFamily::Tcp, repository_name: "xmip-handler-raw-tcp", submodule_path: "handlers/ip/tcp/raw-tcp" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::UdpBase, family: HandlerFamily::Udp, repository_name: "xmip-handler-udp-base", submodule_path: "handlers/ip/udp/base" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::RawUdp, family: HandlerFamily::Udp, repository_name: "xmip-handler-raw-udp", submodule_path: "handlers/ip/udp/raw-udp" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Http, family: HandlerFamily::Http, repository_name: "xmip-handler-http", submodule_path: "handlers/ip/tcp/http" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::WebApi, family: HandlerFamily::Http, repository_name: "xmip-handler-web-api", submodule_path: "handlers/ip/tcp/http/web-api" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Soap, family: HandlerFamily::Http, repository_name: "xmip-handler-soap", submodule_path: "handlers/ip/tcp/http/soap" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::WebSocket, family: HandlerFamily::Http, repository_name: "xmip-handler-websocket", submodule_path: "handlers/ip/tcp/http/websocket" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Grpc, family: HandlerFamily::Grpc, repository_name: "xmip-handler-grpc", submodule_path: "handlers/ip/tcp/grpc" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Mllp, family: HandlerFamily::Healthcare, repository_name: "xmip-handler-mllp", submodule_path: "handlers/ip/tcp/mllp" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::QueueStreamCommon, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-queue-stream-common", submodule_path: "handlers/queue-stream/common" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Msmq, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-msmq", submodule_path: "handlers/queue-stream/msmq" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::RabbitMq, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-rabbitmq", submodule_path: "handlers/queue-stream/rabbitmq" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Kafka, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-kafka", submodule_path: "handlers/queue-stream/apache-kafka" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::IbmMq, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-ibmmq", submodule_path: "handlers/queue-stream/ibmmq" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::AzureServiceBus, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-azure-service-bus", submodule_path: "handlers/queue-stream/azure-service-bus" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::AzureEventGrid, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-azure-event-grid", submodule_path: "handlers/queue-stream/azure-event-grid" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::AwsSqs, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-aws-sqs", submodule_path: "handlers/queue-stream/aws-sqs" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Nats, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-nats", submodule_path: "handlers/queue-stream/nats" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::RedisStreams, family: HandlerFamily::QueueStream, repository_name: "xmip-handler-redis-streams", submodule_path: "handlers/queue-stream/redis-streams" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::IndustrialDeviceCommon, family: HandlerFamily::IndustrialDevice, repository_name: "xmip-handler-industrial-device-common", submodule_path: "handlers/industrial-device/common" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Canbus, family: HandlerFamily::IndustrialDevice, repository_name: "xmip-handler-canbus", submodule_path: "handlers/industrial-device/canbus" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::OpcUa, family: HandlerFamily::IndustrialDevice, repository_name: "xmip-handler-opc-ua", submodule_path: "handlers/industrial-device/opc-ua" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Modbus, family: HandlerFamily::IndustrialDevice, repository_name: "xmip-handler-modbus", submodule_path: "handlers/industrial-device/modbus" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Mqtt, family: HandlerFamily::IndustrialDevice, repository_name: "xmip-handler-mqtt", submodule_path: "handlers/industrial-device/mqtt" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::DataExchangeCommon, family: HandlerFamily::DataExchange, repository_name: "xmip-handler-data-exchange-common", submodule_path: "handlers/data-exchange/common" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Edi, family: HandlerFamily::DataExchange, repository_name: "xmip-handler-edi", submodule_path: "handlers/data-exchange/edi" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Hl7, family: HandlerFamily::DataExchange, repository_name: "xmip-handler-hl7", submodule_path: "handlers/data-exchange/hl7" },
    HandlerTechnologyDescriptor { technology: HandlerTechnology::Fhir, family: HandlerFamily::DataExchange, repository_name: "xmip-handler-fhir", submodule_path: "handlers/data-exchange/fhir" },
];
